version: "3.7"

services:
  app:
    build:
      args:
        user: kira
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: git_explorer
    container_name: github-explorer-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - git_explorer

  nginx:
    image: nginx:latest
    container_name: github-explorer-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    expose:
      - 8000
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - git_explorer

networks:
  git_explorer:
    driver: bridge
